apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-a
spec:
  components:
    - name: app-a
      type: webservice
      properties:
        env:
          - name: OTEL_SERVICE_NAME
            valueFrom:
              configMapKeyRef:
                name: app-a
                key: OTEL_SERVICE_NAME
          - name: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: app-a
                key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
          - name: PYROSCOPE_URL
            valueFrom:
              configMapKeyRef:
                name: app-a
                key: PYROSCOPE_URL
          - name: SERVICE_B_URL
            valueFrom:
              configMapKeyRef:
                name: app-a
                key: SERVICE_B_URL
        image: sselzer/app-a
        port: 8080
      traits:
        - type: annotations
          properties:
            "prometheus.io/scrape": "true"
            "prometheus.io/path": /metrics
            "prometheus.io/port": "8080"
        - type: gateway
          properties:
            domain: app-a.127.0.0.1.nip.io
            http:
              "/": 8080
        - type: cpuscaler
          properties:
            min: 2
            max: 5
            cpuPercent: 80
        - type: resource
          properties:
            cpu: 1
            memory: 256Mi
